#!/bin/bash
# v1 task 13 testing

for file in scripts/t13-*; do
    cat <(echo "-->script:") $file <(echo "---")
    cat $file | sh
    echo "-->$?"
    cat $file | ./hsh
    echo "-->$?"
    diff <(cat $file | sh) <(cat $file | ./hsh)

    echo "-->return or ctrl+d to continue"
    read
done;
