#!/bin/bash
# v1 task 19 testing

for file in scripts/t19-*; do
    cat <(echo "-->script:") $file <(echo "---")
    cat $file | sh
    echo "-->$?"
    cat $file | ./hsh
    echo "-->$?"
    diff <(cat $file | sh) <(cat $file | ./hsh)$

    echo "-->return or ctrl+d to continue"
    read
done;
