#!/bin/bash
# v1 task 14 testing

for file in scripts/t14-*; do
    cat <(echo "-->script:") $file <(echo "---")
    cat $file | sh
    echo "-->$?"
    cat $file | ./hsh
    echo "-->$?"
    cat $file | valgrind --track-fds=yes ./hsh

    echo "-->return or ctrl+d to continue"
    read
done;
