#!/bin/bash
# v1 task 15 testing

for file in scripts/t15-*; do
    cat <(echo "-->script:") $file <(echo "---")
    cat $file | sh
    echo "-->$?"
    cat $file | ./hsh
    echo "-->$?"
    cat $file | valgrind ./hsh

    echo "-->return or ctrl+d to continue"
    read
done;
